import NavBar from "@/components/NavBar";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "PhotoFeed - A personal photo gallery",
  description: "Generated by Hasan U Khan",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NavBar />
        <div className="container my-4 lg:my-8">
          {children}
        </div>
      </body>
    </html>
  );
}
